# Generated by Django 2.2 on 2019-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200, verbose_name='Atividades')),
                ('inicio', models.DateField(null=True, verbose_name='Inicio')),
                ('fim', models.DateField(null=True, verbose_name='Fim')),
            ],
            options={
                'verbose_name': 'Agenda do Evento',
                'verbose_name_plural': 'Agenda do Evento',
            },
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Dados Pessoais',
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoas', models.IntegerField(verbose_name='Quantas Pessoas')),
                ('data', models.DateField(verbose_name='Data Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Inico Evento')),
                ('hora_fim', models.TimeField(verbose_name='Fim Evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('obs', models.TextField(verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Local',
            },
        ),
    ]
