# Generated by Django 2.2 on 2019-04-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoas', models.IntegerField(verbose_name='Quantas Pessoas')),
                ('data', models.CharField(max_length=50, null=True, verbose_name='Data Evento')),
                ('hora_inicio', models.CharField(max_length=50, verbose_name='Inico Evento')),
                ('hora_fim', models.CharField(max_length=50, verbose_name='Fim Evento')),
                ('atividade', models.CharField(max_length=200, verbose_name='Atividades')),
                ('inicio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inicio')),
                ('fim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fim')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('obs', models.CharField(max_length=200, verbose_name='Observação')),
                ('cliente', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
            },
        ),
    ]
