# Generated by Django 2.2 on 2019-04-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevento',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='agendaevento',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
    ]
