# Generated by Django 2.2 on 2019-04-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190409_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaEvento',
        ),
        migrations.DeleteModel(
            name='DadosPessoais',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.AddField(
            model_name='evento',
            name='atividade',
            field=models.CharField(default=1, max_length=200, verbose_name='Atividades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='evento',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(default=1, max_length=150, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(default=1, max_length=150, verbose_name='Nome do Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='obs',
            field=models.TextField(default=1, verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
