# Generated by Django 2.2 on 2019-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20190413_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='obs',
            field=models.CharField(max_length=200, verbose_name='Observação'),
        ),
    ]
