# Generated by Django 2.2 on 2019-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190412_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
